### ISSUE TITLE
How to develop software similar to the OVR Toolkit?

### ISSUE THREAD

**Issue by TitansWhale** [ExtendRealityLtd/VRTK.Tutorials.YouTube#68]
It would be really cool if I could see my heart rate, playtime, and my computer's CPU temperature, among other external information while playing any game. Therefore, as a beginner in Unity, I want to develop an app similar to the OVR Toolkit that can transmit computer information to the VR world without affecting gameplay. How can VRTK be used to achieve this functionality?

**Comment by thestonefox** [comment]
I don't think this would fit within the remit of what VRTK offers, this sort of question is better posted on the general-help channel of the vrtk discord http://community.vrtk.io/
